### ISSUE TITLE
Advanced Planning

### ISSUE THREAD

**Issue by raphael-goetz** [code0-tech/taurus#1]
### Advanced Planning of Execution
 - [ ] Graphical Overview: Provide a visual representation of the execution flow, including all its relationships with other services.
 - [ ] Endpoint Modeling: Define endpoints along with their parameters and configurations.
 - [ ] Feature List & Behaviors: Document features and their associated behaviors for clarity and completeness. E.g. panic when certain things happen

Use plain or add the documentation to the `concept` folder within this repository.

**Comment by nicosammito** [comment]
![Image](https://github.com/user-attachments/assets/a2a189d1-c4c7-4ba2-9491-ca283421e803)

**Infrastructure**

The "Execution" is spliced into two separate parts. We introduce a message broker e.g. RabbitMQ and create topics for each adapter (protocol). Every protocol has a receiving and sending queue to send data and actions across taurus and the linked adapter. 

We call those messages telegrams and every queue can emit a specific amount of telegrams.

For example an adapter receives a request to execute a specific flow. It will prepare the flow and send a "FlowExecution" telegram over the specific protocol queue (e.g. REST_R for REST protocol and the receive queue) to Taurus, which will execute the flow. After finishing it will return the result to the adapter by sending a "FlowResult" telegram (e.g. REST_S for REST protocol and the send queue).

This layer acts as a communication form between the adapter and the execution (Taurus) and each message is either send over the receiving or sending queue of the protocol.

Another example could be a message sending function inside Taurus for WebSockets operations. This internally will just push a message of type WebSocketSendMessage into the WS_S queue with all the information needed to send a certain message to a client connected to the WebSocket adapter.

Each protocol queue (sending and receiving) has own telegram types which are unique to the protocol.

**Taurus internally**

Taurus itself needs to handle the communication to and from the queues. It will mainly run flows and therefore will implement all standard functions and datatypes. At startup it will call Aquila to parse every function and datatype to Sagittarius. 

It will also communicate with Aquila to perform Action calls or retrieve a result.
